
INSERT INTO user_engagement_mis ( 
candidate_id , 
Date_Time ,
Cpu_Count,
Cpu_Working_Time ,
Cpu_idle_Time ,
cpu_percent ,
Usage_cpu_count ,
number_of_software_interrupts_since_boot ,
number_of_system_calls_since_boot ,
number_of_interrupts_since_boot ,
cpu_avg_load_over_1_min ,
cpu_avg_load_over_5_min   ,
cpu_avg_load_over_15_min ,
system_total_memory ,
system_used_memory ,
system_free_memory ,
system_active_memory ,
system_inactive_memory ,
system_buffers_memory ,
system_cached_memory ,
system_shared_memory ,
system_avalible_memory ,
disk_total_memory ,
disk_used_memory ,
disk_free_memory ,
disk_read_count ,
disk_write_count ,
disk_read_bytes ,
disk_write_bytes ,
time_spent_reading_from_disk ,
time_spent_writing_to_disk ,
time_spent_doing_actual_Input_Output ,
number_of_bytes_sent ,
number_of_bytes_received ,
number_of_packets_sent ,
number_of_packets_recived ,
total_number_of_errors_while_receiving ,
total_number_of_errors_while_sending ,
total_number_of_incoming_packets_which_were_dropped ,
total_number_of_outgoing_packets_which_were_dropped ,
boot_time ,
keyboard ,
mouse ,
technology ,
files_changed
)
SELECT 
fc.candidate_id , 
tm.Date_Time ,
tm.Cpu_Count ,
tm.Cpu_Working_Time ,
tm.Cpu_idle_Time ,
tm.cpu_percent ,
tm.Usage_cpu_count ,
tm.number_of_software_interrupts_since_boot ,
tm.number_of_system_calls_since_boot ,
tm.number_of_interrupts_since_boot ,
tm.cpu_avg_load_over_1_min ,
tm.cpu_avg_load_over_5_min   ,
tm.cpu_avg_load_over_15_min ,
tm.system_total_memory ,
tm.system_used_memory ,
tm.system_free_memory ,
tm.system_active_memory ,
tm.system_inactive_memory ,
tm.system_buffers_memory ,
tm.system_cached_memory ,
tm.system_shared_memory ,
tm.system_avalible_memory ,
tm.disk_total_memory ,
tm.disk_used_memory ,
tm.disk_free_memory ,
tm.disk_read_count ,
tm.disk_write_count ,
tm.disk_read_bytes ,
tm.disk_write_bytes ,
tm.time_spent_reading_from_disk ,
tm.time_spent_writing_to_disk ,
tm.time_spent_doing_actual_Input_Output ,
tm.number_of_bytes_sent ,
tm.number_of_bytes_received ,
tm.number_of_packets_sent ,
tm.number_of_packets_recived ,
tm.total_number_of_errors_while_receiving ,
tm.total_number_of_errors_while_sending ,
tm.total_number_of_incoming_packets_which_were_dropped ,
tm.total_number_of_outgoing_packets_which_were_dropped ,
tm.boot_time ,
tm.keyboard ,
tm.mouse ,
tm.technology ,
tm.files_changed 
FROM fellowship_candidate as fc
INNER JOIN temporary_mis as tm
on fc.email = tm.user_name
